#!/bin/bash
# Improvement C: Auto-generate protected-files.conf from project state
# Scans RULES.md for STOP rules, infrastructure scripts, and framework files
# to build a project-aware protection list.
#
# Usage: bash generate-protected-files.sh [project_root]
# Output: writes .claude/hooks/protected-files.conf

set -euo pipefail

PROJECT_ROOT="${1:-.}"
CONF_FILE="$PROJECT_ROOT/.claude/hooks/protected-files.conf"

mkdir -p "$(dirname "$CONF_FILE")"

# Start with header
cat > "$CONF_FILE" << 'HEADER'
# Protected Files — Auto-generated by generate-protected-files.sh
# One pattern per line. Matches against both full path and filename.
# Lines starting with # are comments.
# Regenerate: bash .claude/hooks/generate-protected-files.sh
#
# These files are protected because modifying them without review
# can break the workflow engine, quality gates, or session protocols.

HEADER

# ── Always-protected infrastructure ──
cat >> "$CONF_FILE" << 'ALWAYS'
# Core infrastructure (always protected)
CLAUDE.md
_RULES.md
AGENT_DELEGATION.md
.git/hooks/
frameworks/
.claude/hooks/
.claude/settings.json
ALWAYS

# ── Detect workflow scripts ──
echo "" >> "$CONF_FILE"
echo "# Workflow scripts (detected)" >> "$CONF_FILE"
for script in db_queries.sh session_briefing.sh milestone_check.sh \
              coherence_check.sh coherence_registry.sh build_summarizer.sh \
              save_session.sh work.sh fix.sh harvest.sh generate_board.py; do
    if [ -f "$PROJECT_ROOT/$script" ]; then
        echo "$script" >> "$CONF_FILE"
    fi
done

# ── Detect STOP rule files from RULES.md ──
RULES_FILE=""
for f in "$PROJECT_ROOT"/*_RULES.md; do
    [ -f "$f" ] && RULES_FILE="$f" && break
done

if [ -n "$RULES_FILE" ]; then
    echo "" >> "$CONF_FILE"
    echo "# From STOP rules in $(basename "$RULES_FILE")" >> "$CONF_FILE"

    # Extract file patterns mentioned in STOP rules section
    # Look for lines between "## STOP Rules" and the next "##"
    IN_STOP=false
    while IFS= read -r line; do
        if echo "$line" | grep -qE '^## STOP'; then
            IN_STOP=true
            continue
        fi
        if [ "$IN_STOP" = true ] && echo "$line" | grep -qE '^## '; then
            break
        fi
        if [ "$IN_STOP" = true ]; then
            # Extract file-like patterns: *.db, *.env, etc.
            for pattern in $(echo "$line" | grep -oE '\*\.[a-z]+|[A-Za-z_]+\.(db|env|pem|p12|key)' 2>/dev/null); do
                echo "$pattern" >> "$CONF_FILE"
            done
        fi
    done < "$RULES_FILE"
fi

# ── Detect database files ──
echo "" >> "$CONF_FILE"
echo "# Database files (detected)" >> "$CONF_FILE"
for db in "$PROJECT_ROOT"/*.db; do
    [ -f "$db" ] && echo "$(basename "$db")" >> "$CONF_FILE"
done

# ── Count and report ──
PATTERN_COUNT=$(grep -v '^#' "$CONF_FILE" | grep -v '^$' | wc -l)
echo ""
echo "✅ Generated $CONF_FILE with $PATTERN_COUNT protected patterns"
echo "   Review and customize as needed."
